name: tachyon_api_client
description: Shared API client and authentication service for Tachyon-5.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.3.0

dependencies:
  http: ^1.2.0
  riverpod: ^2.5.1
  tachyon_core:
    path: ../tachyon_core

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
