name: tachyon_web
description: A new Jaspr project
version: 0.0.1

environment:
  sdk: ^3.10.0

dependencies:
  jaspr: ^0.22.1
  jaspr_router: ^0.8.1
  jaspr_riverpod: ^0.4.1
  
  tachyon_core:
    path: ../../packages/tachyon_core
  tachyon_api_client:
    path: ../../packages/tachyon_api_client


dev_dependencies:
  build_runner: ^2.10.0
  build_web_compilers: ^4.4.6
  jaspr_builder: ^0.22.1
  lints: ^5.0.0

jaspr:
  mode: server
  flutter: plugins
